apiVersion: v1
kind: Pod
metadata:
  name: result-app-pod
  labels:
    app: voting-app
spec:
  containers:
    - name: result-app
      image: raghadhabib/result:latest
      ports:
       - containerPort: 80


