apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    app: voting-app
spec:
  type: NodePort
  ports:
    - name: voting-app-port
      port: 80
      targetPort: 80
      nodePort: 30100
      protocol: TCP
  selector:
    app: voting-app

    