apiVersion: v1
kind: Pod
metadata:
  name: voting-app-pod
  labels:
    app: voting-app
spec:
  containers:
    - name: voting-app
      image: raghadhabib/vote:latest
      ports:
       - containerPort: 80


       